# Generated by Django 5.1.7 on 2025-03-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresulttext',
            name='score',
        ),
        migrations.AddField(
            model_name='quizresulttext',
            name='score_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresulttext',
            name='score_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
