# Generated by Django 5.0.2 on 2025-04-05 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/questionnaire/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Questionnaire Question',
                'verbose_name_plural': 'Questionnaire Questions',
                'db_table': 'questionnaire_question',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.questionnairequestion')),
            ],
            options={
                'verbose_name': 'Questionnaire Answer',
                'verbose_name_plural': 'Questionnaire Answers',
                'db_table': 'questionnaire_answer',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.ManyToManyField(related_name='recommendations', to='dashboard.questionnaireanswer')),
            ],
            options={
                'verbose_name': 'Questionnaire Recommendation',
                'verbose_name_plural': 'Questionnaire Recommendations',
                'db_table': 'questionnaire_recommendation',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.ManyToManyField(related_name='results', to='dashboard.questionnaireanswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionnaire Result',
                'verbose_name_plural': 'Questionnaire Results',
                'db_table': 'questionnaire_result',
            },
        ),
    ]
