# Generated by Django 5.2 on 2025-05-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_questionnairequestion_questionnaireanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text="What this vitamin does and why it's important")),
                ('recommended_dose', models.CharField(help_text='Recommended daily dose', max_length=255)),
                ('side_effects', models.TextField(help_text='Possible side effects')),
                ('sources', models.TextField(help_text='Natural sources of this vitamin')),
                ('image', models.ImageField(upload_to='images/vitamins/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vitamin',
                'verbose_name_plural': 'Vitamins',
                'db_table': 'vitamin',
            },
        ),
    ]
