# Generated by Django 5.2 on 2025-05-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_vitamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamin',
            name='critical',
            field=models.BooleanField(default=False, help_text='Is this vitamin critical for pregnancy?'),
        ),
        migrations.AddField(
            model_name='vitamin',
            name='trimester_1',
            field=models.BooleanField(default=False, help_text='Is this vitamin recommended for the first trimester?'),
        ),
        migrations.AddField(
            model_name='vitamin',
            name='trimester_2',
            field=models.BooleanField(default=False, help_text='Is this vitamin recommended for the second trimester?'),
        ),
        migrations.AddField(
            model_name='vitamin',
            name='trimester_3',
            field=models.BooleanField(default=False, help_text='Is this vitamin recommended for the third trimester?'),
        ),
    ]
