# Generated by Django 5.2 on 2025-05-03 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_vitamin_critical_vitamin_trimester_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, help_text="Название класса иконки (например 'fa-yoga')", max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория тренировок',
                'verbose_name_plural': 'Категории тренировок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название уровня')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Значение (1-5)')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тренировки')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (минуты)')),
                ('trimester', models.PositiveSmallIntegerField(choices=[(1, 'Первый триместр'), (2, 'Второй триместр'), (3, 'Третий триместр'), (0, 'Все триместры')], default=0, verbose_name='Триместр')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workouts/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('instructions', models.TextField(verbose_name='Инструкции к упражнениям')),
                ('benefits', models.TextField(blank=True, verbose_name='Польза для беременных')),
                ('contraindications', models.TextField(blank=True, verbose_name='Противопоказания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='dashboard.workoutcategory', verbose_name='Категория')),
                ('difficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='dashboard.workoutdifficulty', verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-created_at'],
            },
        ),
    ]
