# Generated by Django 5.2 on 2025-05-03 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_workoutcategory_workoutdifficulty_workout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient', models.CharField(max_length=100)),
                ('target_amount', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('trimester', models.CharField(choices=[('1', 'First Trimester'), ('2', 'Second Trimester'), ('3', 'Third Trimester'), ('all', 'All Trimesters')], max_length=3)),
                ('color_code', models.CharField(default='#b3a2d1', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(default='#b3a2d1', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='nutrition_images/')),
                ('trimester', models.CharField(choices=[('1', 'First Trimester'), ('2', 'Second Trimester'), ('3', 'Third Trimester'), ('all', 'All Trimesters')], max_length=3)),
                ('description', models.TextField()),
                ('color_code', models.CharField(default='#b3a2d1', max_length=7)),
                ('prep_time', models.PositiveIntegerField(blank=True, null=True)),
                ('cook_time', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('recipe_steps', models.TextField(blank=True, null=True)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('focus', models.CharField(blank=True, max_length=100, null=True)),
                ('read_time', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='trimester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First trimester'), (2, 'Second trimester'), (3, 'Third trimester'), (0, 'All trimesters')], default=0, verbose_name='Триместр'),
        ),
        migrations.CreateModel(
            name='NutritionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.ManyToManyField(related_name='benefits', to='dashboard.nutritioncontent')),
            ],
        ),
        migrations.AddField(
            model_name='nutritioncontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.nutritioncontenttype'),
        ),
        migrations.CreateModel(
            name='NutritionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.FloatField(default=0)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dailyrecommendation')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dashboard.nutritiontracker')),
            ],
        ),
    ]
