# Generated by Django 5.2 on 2025-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dailyrecommendation_nutrientcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecommendation',
            name='category',
            field=models.CharField(choices=[('vitamins', 'Vitamins'), ('minerals', 'Minerals'), ('macronutrients', 'Macronutrients'), ('hydration', 'Hydration'), ('all_nutrients', 'All Nutrients')], default='vitamins', max_length=20),
        ),
    ]
