# Generated by Django 5.2 on 2025-04-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancy', '0002_remove_weekcontent_image_remove_weekcontent_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekcontent',
            name='week_image',
            field=models.ImageField(blank=True, null=True, upload_to='week_images/'),
        ),
    ]
